name: Run Hardhat Test

on: [push]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test_hardhat:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'yarn'
      - name: Yarn Install
        run: corepack yarn@1.22.22 install --frozen-lockfile
      - name: Run All Hardhat Tests
        run: npx hardhat test
      - name: Run hardhat coverage on all Test
        run: npx hardhat test --coverage
